<?php

use Illuminate\Database\Seeder;

class PermissionsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('permissions')->delete();
        
        \DB::table('permissions')->insert(array (
            0 => 
            array (
                'id' => 1,
                'parent_id' => 0,
                'name' => '系统管理',
                'uri' => '',
                'icon' => '&#xe6ae;',
                'guard_name' => 'web',
                'created_at' => '2019-11-11 16:53:41',
                'updated_at' => '2019-11-21 10:37:33',
                'status' => 1,
                'sort' => 15,
            ),
            1 => 
            array (
                'id' => 2,
                'parent_id' => 1,
                'name' => '系统设置',
                'uri' => 'admin.system.settings',
                'icon' => NULL,
                'guard_name' => 'web',
                'created_at' => '2019-11-11 17:57:14',
                'updated_at' => '2019-11-13 17:52:30',
                'status' => 1,
                'sort' => 0,
            ),
            2 => 
            array (
                'id' => 3,
                'parent_id' => 4,
                'name' => '用户管理',
                'uri' => 'admin.users.index',
                'icon' => NULL,
                'guard_name' => 'web',
                'created_at' => '2019-11-12 11:17:19',
                'updated_at' => '2019-11-21 14:01:42',
                'status' => 1,
                'sort' => 10,
            ),
            3 => 
            array (
                'id' => 4,
                'parent_id' => 0,
                'name' => '权限分配',
                'uri' => NULL,
                'icon' => '&#xe70b;',
                'guard_name' => 'web',
                'created_at' => '2019-11-12 11:18:46',
                'updated_at' => '2019-11-21 14:21:37',
                'status' => 1,
                'sort' => 10,
            ),
            4 => 
            array (
                'id' => 5,
                'parent_id' => 0,
                'name' => '客户管理',
                'uri' => NULL,
                'icon' => '&#xe82a;',
                'guard_name' => 'web',
                'created_at' => '2019-11-12 11:56:29',
                'updated_at' => '2019-11-19 11:40:45',
                'status' => 1,
                'sort' => 1,
            ),
            5 => 
            array (
                'id' => 9,
                'parent_id' => 4,
                'name' => '角色管理',
                'uri' => 'admin.roles.index',
                'icon' => NULL,
                'guard_name' => 'web',
                'created_at' => '2019-11-13 17:21:48',
                'updated_at' => '2019-11-21 14:06:02',
                'status' => 1,
                'sort' => 20,
            ),
            6 => 
            array (
                'id' => 10,
                'parent_id' => 4,
                'name' => '添加角色',
                'uri' => 'admin.roles.create',
                'icon' => NULL,
                'guard_name' => 'web',
                'created_at' => '2019-11-13 17:55:46',
                'updated_at' => '2019-11-21 14:06:18',
                'status' => 0,
                'sort' => 21,
            ),
            7 => 
            array (
                'id' => 11,
                'parent_id' => 4,
                'name' => '编辑角色',
                'uri' => 'admin.roles.edit',
                'icon' => NULL,
                'guard_name' => 'web',
                'created_at' => '2019-11-13 17:56:13',
                'updated_at' => '2019-11-21 14:10:00',
                'status' => 0,
                'sort' => 23,
            ),
            8 => 
            array (
                'id' => 12,
                'parent_id' => 4,
                'name' => '删除角色',
                'uri' => 'admin.roles.destroy',
                'icon' => NULL,
                'guard_name' => 'web',
                'created_at' => '2019-11-13 17:56:42',
                'updated_at' => '2019-11-21 14:11:49',
                'status' => 0,
                'sort' => 25,
            ),
            9 => 
            array (
                'id' => 13,
                'parent_id' => 4,
                'name' => '添加用户',
                'uri' => 'admin.users.create',
                'icon' => NULL,
                'guard_name' => 'web',
                'created_at' => '2019-11-18 15:35:59',
                'updated_at' => '2019-11-21 14:02:07',
                'status' => 0,
                'sort' => 11,
            ),
            10 => 
            array (
                'id' => 14,
                'parent_id' => 4,
                'name' => '编辑用户',
                'uri' => 'admin.users.edit',
                'icon' => NULL,
                'guard_name' => 'web',
                'created_at' => NULL,
                'updated_at' => '2019-11-21 14:03:20',
                'status' => 0,
                'sort' => 13,
            ),
            11 => 
            array (
                'id' => 15,
                'parent_id' => 4,
                'name' => '删除用户',
                'uri' => 'admin.users.destroy',
                'icon' => NULL,
                'guard_name' => 'web',
                'created_at' => NULL,
                'updated_at' => '2019-11-21 14:05:25',
                'status' => 0,
                'sort' => 15,
            ),
            12 => 
            array (
                'id' => 16,
                'parent_id' => 0,
                'name' => '订单管理',
                'uri' => NULL,
                'icon' => '&#xe698;',
                'guard_name' => 'web',
                'created_at' => '2019-11-19 11:41:15',
                'updated_at' => '2019-11-21 10:37:15',
                'status' => 1,
                'sort' => 5,
            ),
            13 => 
            array (
                'id' => 17,
                'parent_id' => 0,
                'name' => '系统首页',
                'uri' => NULL,
                'icon' => NULL,
                'guard_name' => 'web',
                'created_at' => '2019-11-21 10:32:22',
                'updated_at' => '2019-11-21 11:06:25',
                'status' => 0,
                'sort' => 0,
            ),
            14 => 
            array (
                'id' => 18,
                'parent_id' => 17,
                'name' => '首页',
                'uri' => 'admin.index',
                'icon' => NULL,
                'guard_name' => 'web',
                'created_at' => '2019-11-21 11:02:45',
                'updated_at' => '2019-11-21 11:05:00',
                'status' => 1,
                'sort' => 0,
            ),
            15 => 
            array (
                'id' => 19,
                'parent_id' => 17,
                'name' => 'Dashboard',
                'uri' => 'admin.dashboard',
                'icon' => NULL,
                'guard_name' => 'web',
                'created_at' => '2019-11-21 11:05:34',
                'updated_at' => '2019-11-21 11:05:34',
                'status' => 1,
                'sort' => 0,
            ),
            16 => 
            array (
                'id' => 20,
                'parent_id' => 4,
                'name' => '权限菜单',
                'uri' => 'admin.permissions.index',
                'icon' => NULL,
                'guard_name' => 'web',
                'created_at' => '2019-11-21 11:11:44',
                'updated_at' => '2019-11-21 11:29:07',
                'status' => 0,
                'sort' => 0,
            ),
            17 => 
            array (
                'id' => 21,
                'parent_id' => 4,
                'name' => '添加权限菜单',
                'uri' => 'admin.permissions.create',
                'icon' => NULL,
                'guard_name' => 'web',
                'created_at' => '2019-11-21 11:14:14',
                'updated_at' => '2019-11-21 11:17:55',
                'status' => 0,
                'sort' => 0,
            ),
            18 => 
            array (
                'id' => 22,
                'parent_id' => 4,
                'name' => '编辑权限菜单',
                'uri' => 'admin.permissions.edit',
                'icon' => NULL,
                'guard_name' => 'web',
                'created_at' => '2019-11-21 11:17:01',
                'updated_at' => '2019-11-21 11:17:55',
                'status' => 0,
                'sort' => 0,
            ),
            19 => 
            array (
                'id' => 23,
                'parent_id' => 4,
                'name' => '删除权限菜单',
                'uri' => 'admin.permissions.destroy',
                'icon' => NULL,
                'guard_name' => 'web',
                'created_at' => '2019-11-21 11:17:39',
                'updated_at' => '2019-11-21 11:17:39',
                'status' => 0,
                'sort' => 0,
            ),
            20 => 
            array (
                'id' => 24,
                'parent_id' => 4,
                'name' => '保存添加用户',
                'uri' => 'admin.users.store',
                'icon' => NULL,
                'guard_name' => 'web',
                'created_at' => '2019-11-21 14:02:59',
                'updated_at' => '2019-11-21 14:03:07',
                'status' => 0,
                'sort' => 12,
            ),
            21 => 
            array (
                'id' => 25,
                'parent_id' => 4,
                'name' => '保存编辑用户',
                'uri' => 'admin.users.update',
                'icon' => NULL,
                'guard_name' => 'web',
                'created_at' => '2019-11-21 14:04:06',
                'updated_at' => '2019-11-21 14:04:06',
                'status' => 0,
                'sort' => 14,
            ),
            22 => 
            array (
                'id' => 26,
                'parent_id' => 4,
                'name' => '保存添加角色',
                'uri' => 'admin.roles.store',
                'icon' => NULL,
                'guard_name' => 'web',
                'created_at' => '2019-11-21 14:07:06',
                'updated_at' => '2019-11-21 14:07:06',
                'status' => 0,
                'sort' => 22,
            ),
            23 => 
            array (
                'id' => 27,
                'parent_id' => 4,
                'name' => '保存编辑角色',
                'uri' => 'admin.roles.update',
                'icon' => NULL,
                'guard_name' => 'web',
                'created_at' => '2019-11-21 14:11:26',
                'updated_at' => '2019-11-21 14:11:26',
                'status' => 0,
                'sort' => 24,
            ),
            24 => 
            array (
                'id' => 28,
                'parent_id' => 5,
                'name' => '客户列表',
                'uri' => 'admin.customer.index',
                'icon' => NULL,
                'guard_name' => 'web',
                'created_at' => '2019-11-21 14:37:05',
                'updated_at' => '2019-11-21 14:37:05',
                'status' => 1,
                'sort' => 0,
            ),
            25 => 
            array (
                'id' => 29,
                'parent_id' => 5,
                'name' => '添加客户',
                'uri' => 'admin.customer.create',
                'icon' => NULL,
                'guard_name' => 'web',
                'created_at' => '2019-11-21 15:34:11',
                'updated_at' => '2019-11-21 15:34:11',
                'status' => 0,
                'sort' => 0,
            ),
            26 => 
            array (
                'id' => 30,
                'parent_id' => 5,
                'name' => '保存添加客户',
                'uri' => 'admin.customer.store',
                'icon' => NULL,
                'guard_name' => 'web',
                'created_at' => '2019-11-21 15:34:46',
                'updated_at' => '2019-11-21 15:34:46',
                'status' => 0,
                'sort' => 0,
            ),
            27 => 
            array (
                'id' => 31,
                'parent_id' => 5,
                'name' => '编辑客户',
                'uri' => 'admin.customer.edit',
                'icon' => NULL,
                'guard_name' => 'web',
                'created_at' => '2019-11-21 15:35:38',
                'updated_at' => '2019-11-21 15:35:38',
                'status' => 0,
                'sort' => 0,
            ),
            28 => 
            array (
                'id' => 32,
                'parent_id' => 5,
                'name' => '保存编辑客户',
                'uri' => 'admin.customer.update',
                'icon' => NULL,
                'guard_name' => 'web',
                'created_at' => '2019-11-21 15:36:14',
                'updated_at' => '2019-11-21 17:24:47',
                'status' => 0,
                'sort' => 0,
            ),
            29 => 
            array (
                'id' => 33,
                'parent_id' => 5,
                'name' => '删除客户',
                'uri' => 'admin.customer.destroy',
                'icon' => NULL,
                'guard_name' => 'web',
                'created_at' => '2019-11-21 15:36:56',
                'updated_at' => '2019-11-21 15:36:56',
                'status' => 0,
                'sort' => 0,
            ),
            30 => 
            array (
                'id' => 34,
                'parent_id' => 5,
                'name' => '客户标签',
                'uri' => 'admin.tags.index',
                'icon' => NULL,
                'guard_name' => 'web',
                'created_at' => '2019-11-21 15:36:56',
                'updated_at' => NULL,
                'status' => 1,
                'sort' => 0,
            ),
            31 => 
            array (
                'id' => 35,
                'parent_id' => 5,
                'name' => '添加标签',
                'uri' => 'admin.tags.create',
                'icon' => NULL,
                'guard_name' => 'web',
                'created_at' => '2019-11-21 15:36:56',
                'updated_at' => NULL,
                'status' => 0,
                'sort' => 0,
            ),
            32 => 
            array (
                'id' => 36,
                'parent_id' => 5,
                'name' => '保存添加标签',
                'uri' => 'admin.tags.store',
                'icon' => NULL,
                'guard_name' => 'web',
                'created_at' => NULL,
                'updated_at' => NULL,
                'status' => 0,
                'sort' => 0,
            ),
            33 => 
            array (
                'id' => 37,
                'parent_id' => 5,
                'name' => '编辑标签',
                'uri' => 'admin.tags.edit',
                'icon' => NULL,
                'guard_name' => 'web',
                'created_at' => NULL,
                'updated_at' => NULL,
                'status' => 0,
                'sort' => 0,
            ),
            34 => 
            array (
                'id' => 38,
                'parent_id' => 5,
                'name' => '保存编辑标签',
                'uri' => 'admin.tags.update',
                'icon' => NULL,
                'guard_name' => 'web',
                'created_at' => NULL,
                'updated_at' => NULL,
                'status' => 0,
                'sort' => 0,
            ),
            35 => 
            array (
                'id' => 39,
                'parent_id' => 5,
                'name' => '删除标签',
                'uri' => 'admin.tags.destroy',
                'icon' => NULL,
                'guard_name' => 'web',
                'created_at' => NULL,
                'updated_at' => NULL,
                'status' => 0,
                'sort' => 0,
            ),
            36 => 
            array (
                'id' => 40,
                'parent_id' => 5,
                'name' => '客户来源',
                'uri' => 'admin.source.index',
                'icon' => NULL,
                'guard_name' => 'web',
                'created_at' => NULL,
                'updated_at' => NULL,
                'status' => 1,
                'sort' => 0,
            ),
            37 => 
            array (
                'id' => 41,
                'parent_id' => 5,
                'name' => '添加来源',
                'uri' => 'admin.source.create',
                'icon' => NULL,
                'guard_name' => 'web',
                'created_at' => NULL,
                'updated_at' => NULL,
                'status' => 0,
                'sort' => 0,
            ),
            38 => 
            array (
                'id' => 42,
                'parent_id' => 5,
                'name' => '保存添加来源',
                'uri' => 'admin.source.store',
                'icon' => NULL,
                'guard_name' => 'web',
                'created_at' => NULL,
                'updated_at' => NULL,
                'status' => 0,
                'sort' => 0,
            ),
            39 => 
            array (
                'id' => 43,
                'parent_id' => 5,
                'name' => '编辑来源',
                'uri' => 'admin.source.edit',
                'icon' => NULL,
                'guard_name' => 'web',
                'created_at' => NULL,
                'updated_at' => NULL,
                'status' => 0,
                'sort' => 0,
            ),
            40 => 
            array (
                'id' => 44,
                'parent_id' => 5,
                'name' => '保存编辑来源',
                'uri' => 'admin.source.update',
                'icon' => NULL,
                'guard_name' => 'web',
                'created_at' => NULL,
                'updated_at' => NULL,
                'status' => 0,
                'sort' => 0,
            ),
            41 => 
            array (
                'id' => 45,
                'parent_id' => 5,
                'name' => '删除来源',
                'uri' => 'admin.source.destroy',
                'icon' => NULL,
                'guard_name' => 'web',
                'created_at' => NULL,
                'updated_at' => NULL,
                'status' => 0,
                'sort' => 0,
            ),
            42 => 
            array (
                'id' => 46,
                'parent_id' => 1,
                'name' => '查看全部数据',
                'uri' => NULL,
                'icon' => NULL,
                'guard_name' => 'web',
                'created_at' => '2019-11-22 16:32:55',
                'updated_at' => '2019-11-22 16:32:55',
                'status' => 0,
                'sort' => 0,
            ),
            43 => 
            array (
                'id' => 47,
                'parent_id' => 0,
                'name' => '提醒管理',
                'uri' => NULL,
                'icon' => '&#xe611;',
                'guard_name' => 'web',
                'created_at' => '2019-11-23 03:15:52',
                'updated_at' => '2019-11-23 03:15:52',
                'status' => 1,
                'sort' => 8,
            ),
            44 => 
            array (
                'id' => 50,
                'parent_id' => 47,
                'name' => '回访提醒',
                'uri' => 'admin.remind.index',
                'icon' => NULL,
                'guard_name' => 'web',
                'created_at' => NULL,
                'updated_at' => NULL,
                'status' => 1,
                'sort' => 0,
            ),
            45 => 
            array (
                'id' => 51,
                'parent_id' => 47,
                'name' => '添加提醒',
                'uri' => 'admin.remind.create',
                'icon' => NULL,
                'guard_name' => 'web',
                'created_at' => NULL,
                'updated_at' => NULL,
                'status' => 0,
                'sort' => 0,
            ),
            46 => 
            array (
                'id' => 52,
                'parent_id' => 47,
                'name' => '保存添加提醒',
                'uri' => 'admin.remind.store',
                'icon' => NULL,
                'guard_name' => 'web',
                'created_at' => NULL,
                'updated_at' => NULL,
                'status' => 0,
                'sort' => 0,
            ),
            47 => 
            array (
                'id' => 53,
                'parent_id' => 47,
                'name' => '编辑提醒',
                'uri' => 'admin.remind.edit',
                'icon' => NULL,
                'guard_name' => 'web',
                'created_at' => NULL,
                'updated_at' => NULL,
                'status' => 0,
                'sort' => 0,
            ),
            48 => 
            array (
                'id' => 54,
                'parent_id' => 47,
                'name' => '保存编辑提醒',
                'uri' => 'admin.remind.update',
                'icon' => NULL,
                'guard_name' => 'web',
                'created_at' => NULL,
                'updated_at' => NULL,
                'status' => 0,
                'sort' => 0,
            ),
            49 => 
            array (
                'id' => 55,
                'parent_id' => 47,
                'name' => '删除提醒',
                'uri' => 'admin.remind.destroy',
                'icon' => NULL,
                'guard_name' => 'web',
                'created_at' => NULL,
                'updated_at' => NULL,
                'status' => 0,
                'sort' => 0,
            ),
            50 => 
            array (
                'id' => 56,
                'parent_id' => 5,
                'name' => '退回客户',
                'uri' => 'admin.customer.return',
                'icon' => NULL,
                'guard_name' => 'web',
                'created_at' => '2019-11-29 10:55:21',
                'updated_at' => '2019-11-29 10:55:21',
                'status' => 0,
                'sort' => 0,
            ),
            51 => 
            array (
                'id' => 57,
                'parent_id' => 5,
                'name' => '客户公海',
                'uri' => 'admin.sea.index',
                'icon' => NULL,
                'guard_name' => 'web',
                'created_at' => '2019-11-29 10:56:02',
                'updated_at' => '2019-11-29 10:56:02',
                'status' => 1,
                'sort' => 0,
            ),
            52 => 
            array (
                'id' => 58,
                'parent_id' => 5,
                'name' => '保存分配客户',
                'uri' => 'admin.sea.update',
                'icon' => NULL,
                'guard_name' => 'web',
                'created_at' => '2019-11-29 10:56:44',
                'updated_at' => '2019-11-29 10:56:44',
                'status' => 0,
                'sort' => 0,
            ),
            53 => 
            array (
                'id' => 59,
                'parent_id' => 5,
                'name' => '领取客户',
                'uri' => 'admin.sea.store',
                'icon' => NULL,
                'guard_name' => 'web',
                'created_at' => '2019-11-29 10:57:06',
                'updated_at' => '2019-11-29 10:57:06',
                'status' => 0,
                'sort' => 0,
            ),
            54 => 
            array (
                'id' => 60,
                'parent_id' => 47,
                'name' => '查看提醒',
                'uri' => 'admin.remind.show',
                'icon' => NULL,
                'guard_name' => 'web',
                'created_at' => '2019-11-29 10:59:50',
                'updated_at' => '2019-11-29 10:59:50',
                'status' => 0,
                'sort' => 0,
            ),
            55 => 
            array (
                'id' => 61,
                'parent_id' => 16,
                'name' => '订单列表',
                'uri' => 'admin.orders.index',
                'icon' => NULL,
                'guard_name' => 'web',
                'created_at' => NULL,
                'updated_at' => NULL,
                'status' => 1,
                'sort' => 0,
            ),
            56 => 
            array (
                'id' => 62,
                'parent_id' => 16,
                'name' => '添加订单',
                'uri' => 'admin.orders.create',
                'icon' => NULL,
                'guard_name' => 'web',
                'created_at' => NULL,
                'updated_at' => NULL,
                'status' => 0,
                'sort' => 0,
            ),
            57 => 
            array (
                'id' => 63,
                'parent_id' => 16,
                'name' => '保存添加订单',
                'uri' => 'admin.orders.store',
                'icon' => NULL,
                'guard_name' => 'web',
                'created_at' => NULL,
                'updated_at' => NULL,
                'status' => 0,
                'sort' => 0,
            ),
            58 => 
            array (
                'id' => 64,
                'parent_id' => 16,
                'name' => '编辑订单',
                'uri' => 'admin.orders.edit',
                'icon' => NULL,
                'guard_name' => 'web',
                'created_at' => NULL,
                'updated_at' => NULL,
                'status' => 0,
                'sort' => 0,
            ),
            59 => 
            array (
                'id' => 65,
                'parent_id' => 16,
                'name' => '保存编辑订单',
                'uri' => 'admin.orders.update',
                'icon' => NULL,
                'guard_name' => 'web',
                'created_at' => NULL,
                'updated_at' => NULL,
                'status' => 0,
                'sort' => 0,
            ),
            60 => 
            array (
                'id' => 66,
                'parent_id' => 16,
                'name' => '删除订单',
                'uri' => 'admin.orders.destroy',
                'icon' => NULL,
                'guard_name' => 'web',
                'created_at' => NULL,
                'updated_at' => NULL,
                'status' => 0,
                'sort' => 0,
            ),
            61 => 
            array (
                'id' => 67,
                'parent_id' => 16,
                'name' => '订单详情',
                'uri' => 'admin.orders.show',
                'icon' => NULL,
                'guard_name' => 'web',
                'created_at' => NULL,
                'updated_at' => NULL,
                'status' => 0,
                'sort' => 0,
            ),
            62 => 
            array (
                'id' => 68,
                'parent_id' => 16,
                'name' => '回款记录',
                'uri' => 'admin.orders.back',
                'icon' => NULL,
                'guard_name' => 'web',
                'created_at' => NULL,
                'updated_at' => NULL,
                'status' => 0,
                'sort' => 0,
            ),
            63 => 
            array (
                'id' => 69,
                'parent_id' => 16,
                'name' => '合同列表',
                'uri' => 'admin.contract.index',
                'icon' => NULL,
                'guard_name' => 'web',
                'created_at' => NULL,
                'updated_at' => NULL,
                'status' => 1,
                'sort' => 0,
            ),
            64 => 
            array (
                'id' => 70,
                'parent_id' => 16,
                'name' => '添加合同',
                'uri' => 'admin.contract.create',
                'icon' => NULL,
                'guard_name' => 'web',
                'created_at' => NULL,
                'updated_at' => NULL,
                'status' => 0,
                'sort' => 0,
            ),
            65 => 
            array (
                'id' => 71,
                'parent_id' => 16,
                'name' => '保存添加合同',
                'uri' => 'admin.contract.store',
                'icon' => NULL,
                'guard_name' => 'web',
                'created_at' => NULL,
                'updated_at' => NULL,
                'status' => 0,
                'sort' => 0,
            ),
            66 => 
            array (
                'id' => 72,
                'parent_id' => 16,
                'name' => '编辑合同',
                'uri' => 'admin.contract.edit',
                'icon' => NULL,
                'guard_name' => 'web',
                'created_at' => NULL,
                'updated_at' => NULL,
                'status' => 0,
                'sort' => 0,
            ),
            67 => 
            array (
                'id' => 73,
                'parent_id' => 16,
                'name' => '保存编辑合同',
                'uri' => 'admin.contract.update',
                'icon' => NULL,
                'guard_name' => 'web',
                'created_at' => NULL,
                'updated_at' => NULL,
                'status' => 0,
                'sort' => 0,
            ),
            68 => 
            array (
                'id' => 74,
                'parent_id' => 16,
                'name' => '删除合同',
                'uri' => 'admin.contract.destroy',
                'icon' => NULL,
                'guard_name' => 'web',
                'created_at' => NULL,
                'updated_at' => NULL,
                'status' => 0,
                'sort' => 0,
            ),
            69 => 
            array (
                'id' => 75,
                'parent_id' => 16,
                'name' => '业务种类',
                'uri' => 'admin.goods.index',
                'icon' => NULL,
                'guard_name' => 'web',
                'created_at' => NULL,
                'updated_at' => NULL,
                'status' => 1,
                'sort' => 0,
            ),
            70 => 
            array (
                'id' => 76,
                'parent_id' => 16,
                'name' => '添加业务种类',
                'uri' => 'admin.goods.create',
                'icon' => NULL,
                'guard_name' => 'web',
                'created_at' => NULL,
                'updated_at' => NULL,
                'status' => 0,
                'sort' => 0,
            ),
            71 => 
            array (
                'id' => 77,
                'parent_id' => 16,
                'name' => '保存添加业务种类',
                'uri' => 'admin.goods.store',
                'icon' => NULL,
                'guard_name' => 'web',
                'created_at' => NULL,
                'updated_at' => NULL,
                'status' => 0,
                'sort' => 0,
            ),
            72 => 
            array (
                'id' => 78,
                'parent_id' => 16,
                'name' => '编辑业务种类',
                'uri' => 'admin.goods.edit',
                'icon' => NULL,
                'guard_name' => 'web',
                'created_at' => NULL,
                'updated_at' => NULL,
                'status' => 0,
                'sort' => 0,
            ),
            73 => 
            array (
                'id' => 79,
                'parent_id' => 16,
                'name' => '保存编辑业务种类',
                'uri' => 'admin.goods.update',
                'icon' => NULL,
                'guard_name' => 'web',
                'created_at' => NULL,
                'updated_at' => NULL,
                'status' => 0,
                'sort' => 0,
            ),
            74 => 
            array (
                'id' => 80,
                'parent_id' => 16,
                'name' => '删除业务种类',
                'uri' => 'admin.goods.destroy',
                'icon' => NULL,
                'guard_name' => 'web',
                'created_at' => NULL,
                'updated_at' => NULL,
                'status' => 0,
                'sort' => 0,
            ),
            75 => 
            array (
                'id' => 81,
                'parent_id' => 16,
                'name' => '删除附件',
                'uri' => 'admin.orders.delimage',
                'icon' => NULL,
                'guard_name' => 'web',
                'created_at' => '2019-12-12 10:15:10',
                'updated_at' => '2019-12-12 10:15:10',
                'status' => 0,
                'sort' => 0,
            ),
            76 => 
            array (
                'id' => 82,
                'parent_id' => 16,
                'name' => '订单退款',
                'uri' => 'admin.orders.refund',
                'icon' => NULL,
                'guard_name' => 'web',
                'created_at' => '2019-12-12 10:15:49',
                'updated_at' => '2019-12-12 10:15:49',
                'status' => 0,
                'sort' => 0,
            ),
            77 => 
            array (
                'id' => 83,
                'parent_id' => 5,
                'name' => '客户分析',
                'uri' => 'admin.customer.analysi',
                'icon' => NULL,
                'guard_name' => 'web',
                'created_at' => '2019-12-12 10:15:49',
                'updated_at' => '2019-12-12 10:15:49',
                'status' => 1,
                'sort' => 0,
            ),
            78 => 
            array (
                'id' => 84,
                'parent_id' => 16,
                'name' => '订单分析',
                'uri' => 'admin.orders.analysi',
                'icon' => NULL,
                'guard_name' => 'web',
                'created_at' => '2019-12-12 10:15:49',
                'updated_at' => '2019-12-12 10:15:49',
                'status' => 1,
                'sort' => 0,
            ),
            79 => 
            array (
                'id' => 85,
                'parent_id' => 16,
                'name' => '合同详情',
                'uri' => 'admin.contract.show',
                'icon' => NULL,
                'guard_name' => 'web',
                'created_at' => NULL,
                'updated_at' => NULL,
                'status' => 0,
                'sort' => 0,
            ),
            80 => 
            array (
                'id' => 86,
                'parent_id' => 5,
                'name' => '分配客户',
                'uri' => 'admin.sea.edit',
                'icon' => NULL,
                'guard_name' => 'web',
                'created_at' => NULL,
                'updated_at' => NULL,
                'status' => 0,
                'sort' => 0,
            ),
            81 => 
            array (
                'id' => 87,
                'parent_id' => 1,
                'name' => '操作日志',
                'uri' => 'admin.system.logs',
                'icon' => NULL,
                'guard_name' => 'web',
                'created_at' => NULL,
                'updated_at' => NULL,
                'status' => 1,
                'sort' => 0,
            ),
            82 => 
            array (
                'id' => 88,
                'parent_id' => 4,
                'name' => '用户等级',
                'uri' => 'admin.grade.index',
                'icon' => NULL,
                'guard_name' => 'web',
                'created_at' => NULL,
                'updated_at' => NULL,
                'status' => 1,
                'sort' => 0,
            ),
            83 => 
            array (
                'id' => 89,
                'parent_id' => 1,
                'name' => '订单审核',
                'uri' => 'admin.orders.verify',
                'icon' => NULL,
                'guard_name' => 'web',
                'created_at' => NULL,
                'updated_at' => NULL,
                'status' => 0,
                'sort' => 0,
            ),
            84 => 
            array (
                'id' => 90,
                'parent_id' => 5,
                'name' => '客户详情',
                'uri' => 'admin.customer.show',
                'icon' => NULL,
                'guard_name' => 'web',
                'created_at' => NULL,
                'updated_at' => NULL,
                'status' => 0,
                'sort' => 0,
            ),
            85 => 
            array (
                'id' => 91,
                'parent_id' => 5,
                'name' => '客户银行',
                'uri' => 'admin.bank.index',
                'icon' => NULL,
                'guard_name' => 'web',
                'created_at' => NULL,
                'updated_at' => NULL,
                'status' => 0,
                'sort' => 0,
            ),
            86 => 
            array (
                'id' => 92,
                'parent_id' => 5,
                'name' => '添加银行',
                'uri' => 'admin.bank.create',
                'icon' => NULL,
                'guard_name' => 'web',
                'created_at' => NULL,
                'updated_at' => NULL,
                'status' => 0,
                'sort' => 0,
            ),
            87 => 
            array (
                'id' => 93,
                'parent_id' => 5,
                'name' => '添加保存银行',
                'uri' => 'admin.bank.store',
                'icon' => NULL,
                'guard_name' => 'web',
                'created_at' => NULL,
                'updated_at' => NULL,
                'status' => 0,
                'sort' => 0,
            ),
            88 => 
            array (
                'id' => 94,
                'parent_id' => 5,
                'name' => '编辑银行',
                'uri' => 'admin.bank.edit',
                'icon' => NULL,
                'guard_name' => 'web',
                'created_at' => NULL,
                'updated_at' => NULL,
                'status' => 0,
                'sort' => 0,
            ),
            89 => 
            array (
                'id' => 95,
                'parent_id' => 5,
                'name' => '编辑保存银行',
                'uri' => 'admin.bank.update',
                'icon' => NULL,
                'guard_name' => 'web',
                'created_at' => NULL,
                'updated_at' => NULL,
                'status' => 0,
                'sort' => 0,
            ),
            90 => 
            array (
                'id' => 96,
                'parent_id' => 5,
                'name' => '删除银行',
                'uri' => 'admin.bank.destroy',
                'icon' => NULL,
                'guard_name' => 'web',
                'created_at' => NULL,
                'updated_at' => NULL,
                'status' => 0,
                'sort' => 0,
            ),
            91 => 
            array (
                'id' => 97,
                'parent_id' => 5,
                'name' => '跟进记录',
                'uri' => 'admin.fup.index',
                'icon' => NULL,
                'guard_name' => 'web',
                'created_at' => NULL,
                'updated_at' => NULL,
                'status' => 0,
                'sort' => 0,
            ),
            92 => 
            array (
                'id' => 98,
                'parent_id' => 5,
                'name' => '保存跟进记录',
                'uri' => 'admin.fup.store',
                'icon' => NULL,
                'guard_name' => 'web',
                'created_at' => NULL,
                'updated_at' => NULL,
                'status' => 0,
                'sort' => 0,
            ),
            93 => 
            array (
                'id' => 99,
                'parent_id' => 16,
                'name' => '业务节点状态列表',
                'uri' => 'admin.orders.process',
                'icon' => NULL,
                'guard_name' => 'web',
                'created_at' => NULL,
                'updated_at' => NULL,
                'status' => 0,
                'sort' => 0,
            ),
            94 => 
            array (
                'id' => 100,
                'parent_id' => 16,
                'name' => '编辑业务节点状态',
                'uri' => 'admin.orders.processedit',
                'icon' => NULL,
                'guard_name' => 'web',
                'created_at' => NULL,
                'updated_at' => NULL,
                'status' => 0,
                'sort' => 0,
            ),
            95 => 
            array (
                'id' => 101,
                'parent_id' => 16,
                'name' => '业务节点状态记录',
                'uri' => 'admin.orders.detail',
                'icon' => NULL,
                'guard_name' => 'web',
                'created_at' => NULL,
                'updated_at' => NULL,
                'status' => 0,
                'sort' => 0,
            ),
            96 => 
            array (
                'id' => 102,
                'parent_id' => 1,
                'name' => '编辑订单状态',
                'uri' => 'admin.orders.stop',
                'icon' => NULL,
                'guard_name' => 'web',
                'created_at' => NULL,
                'updated_at' => NULL,
                'status' => 0,
                'sort' => 0,
            ),
            97 => 
            array (
                'id' => 103,
                'parent_id' => 16,
                'name' => '退款审核',
                'uri' => 'admin.orders.examine',
                'icon' => NULL,
                'guard_name' => 'web',
                'created_at' => NULL,
                'updated_at' => NULL,
                'status' => 0,
                'sort' => 0,
            ),
            98 => 
            array (
                'id' => 104,
                'parent_id' => 5,
                'name' => '客户领取分配记录',
                'uri' => 'admin.customer.record',
                'icon' => NULL,
                'guard_name' => 'web',
                'created_at' => NULL,
                'updated_at' => NULL,
                'status' => 0,
                'sort' => 0,
            ),
            99 => 
            array (
                'id' => 105,
                'parent_id' => 16,
                'name' => '技术部成本',
                'uri' => 'admin.orders.jscost',
                'icon' => NULL,
                'guard_name' => 'web',
                'created_at' => NULL,
                'updated_at' => NULL,
                'status' => 0,
                'sort' => 0,
            ),
            100 => 
            array (
                'id' => 106,
                'parent_id' => 16,
                'name' => '资质列表',
                'uri' => 'admin.contract.qualified',
                'icon' => NULL,
                'guard_name' => 'web',
                'created_at' => NULL,
                'updated_at' => NULL,
                'status' => 1,
                'sort' => 0,
            ),
            101 => 
            array (
                'id' => 107,
                'parent_id' => 16,
                'name' => '订单操作日志',
                'uri' => 'admin.orders.logs',
                'icon' => NULL,
                'guard_name' => 'web',
                'created_at' => NULL,
                'updated_at' => NULL,
                'status' => 1,
                'sort' => 0,
            ),
            102 => 
            array (
                'id' => 108,
                'parent_id' => 16,
                'name' => '对接订单列表',
                'uri' => 'admin.abutment.index',
                'icon' => NULL,
                'guard_name' => 'web',
                'created_at' => NULL,
                'updated_at' => NULL,
                'status' => 1,
                'sort' => 0,
            ),
            103 => 
            array (
                'id' => 109,
                'parent_id' => 16,
                'name' => '添加对接订单',
                'uri' => 'admin.abutment.create',
                'icon' => NULL,
                'guard_name' => 'web',
                'created_at' => NULL,
                'updated_at' => NULL,
                'status' => 0,
                'sort' => 0,
            ),
            104 => 
            array (
                'id' => 110,
                'parent_id' => 16,
                'name' => '保存对接订单',
                'uri' => 'admin.abutment.store',
                'icon' => NULL,
                'guard_name' => 'web',
                'created_at' => NULL,
                'updated_at' => NULL,
                'status' => 0,
                'sort' => 0,
            ),
            105 => 
            array (
                'id' => 111,
                'parent_id' => 16,
                'name' => '编辑对接订单',
                'uri' => 'admin.abutment.edit',
                'icon' => NULL,
                'guard_name' => 'web',
                'created_at' => NULL,
                'updated_at' => NULL,
                'status' => 0,
                'sort' => 0,
            ),
            106 => 
            array (
                'id' => 112,
                'parent_id' => 16,
                'name' => '编辑保存对接订单',
                'uri' => 'admin.abutment.update',
                'icon' => NULL,
                'guard_name' => 'web',
                'created_at' => NULL,
                'updated_at' => NULL,
                'status' => 0,
                'sort' => 0,
            ),
            107 => 
            array (
                'id' => 113,
                'parent_id' => 16,
                'name' => '删除对接订单',
                'uri' => 'admin.abutment.destroy',
                'icon' => NULL,
                'guard_name' => 'web',
                'created_at' => NULL,
                'updated_at' => NULL,
                'status' => 0,
                'sort' => 0,
            ),
            108 => 
            array (
                'id' => 114,
                'parent_id' => 16,
                'name' => '对接订单详情',
                'uri' => 'admin.abutment.show',
                'icon' => NULL,
                'guard_name' => 'web',
                'created_at' => NULL,
                'updated_at' => NULL,
                'status' => 0,
                'sort' => 0,
            ),
            109 => 
            array (
                'id' => 115,
                'parent_id' => 16,
                'name' => '维保订单列表',
                'uri' => 'admin.maintenance.index',
                'icon' => NULL,
                'guard_name' => 'web',
                'created_at' => NULL,
                'updated_at' => NULL,
                'status' => 1,
                'sort' => 0,
            ),
            110 => 
            array (
                'id' => 116,
                'parent_id' => 16,
                'name' => '添加维保订单',
                'uri' => 'admin.maintenance.create',
                'icon' => NULL,
                'guard_name' => 'web',
                'created_at' => NULL,
                'updated_at' => NULL,
                'status' => 0,
                'sort' => 0,
            ),
            111 => 
            array (
                'id' => 117,
                'parent_id' => 16,
                'name' => '保存维保订单',
                'uri' => 'admin.maintenance.store',
                'icon' => NULL,
                'guard_name' => 'web',
                'created_at' => NULL,
                'updated_at' => NULL,
                'status' => 0,
                'sort' => 0,
            ),
            112 => 
            array (
                'id' => 118,
                'parent_id' => 16,
                'name' => '编辑维保订单',
                'uri' => 'admin.maintenance.edit',
                'icon' => NULL,
                'guard_name' => 'web',
                'created_at' => NULL,
                'updated_at' => NULL,
                'status' => 0,
                'sort' => 0,
            ),
            113 => 
            array (
                'id' => 119,
                'parent_id' => 16,
                'name' => '编辑保存维保订单',
                'uri' => 'admin.maintenance.update',
                'icon' => NULL,
                'guard_name' => 'web',
                'created_at' => NULL,
                'updated_at' => NULL,
                'status' => 0,
                'sort' => 0,
            ),
            114 => 
            array (
                'id' => 120,
                'parent_id' => 16,
                'name' => '删除维保订单',
                'uri' => 'admin.maintenance.destroy',
                'icon' => NULL,
                'guard_name' => 'web',
                'created_at' => NULL,
                'updated_at' => NULL,
                'status' => 0,
                'sort' => 0,
            ),
            115 => 
            array (
                'id' => 121,
                'parent_id' => 16,
                'name' => '维保订单详情',
                'uri' => 'admin.maintenance.show',
                'icon' => NULL,
                'guard_name' => 'web',
                'created_at' => NULL,
                'updated_at' => NULL,
                'status' => 0,
                'sort' => 0,
            ),
        ));
        
        
    }
}